### ISSUE TITLE
Stalled after some time

### ISSUE THREAD

**Issue by latot** [gosom/google-maps-scraper#11]
Hi, I tested this with some samples, no idea why, but the program does not finish, some process seems to be working more than 7h without finish....

I'm uploading the query file
[requests.txt](https://github.com/gosom/google-maps-scraper/files/12465675/requests.txt)

Thx!

**Comment by gosom** [comment]
Hi @latot, 

the program does not exit when the requests are completed.

Does the output file contains results?

**Comment by latot** [comment]
Yes, it has the results. Is possible to finish it when is ready with the requests? or is there a reason why this behavior?

**Comment by ntrance** [comment]
I have the same issue on Windows the cmd window hangs until I escape it and then it writes the CSV file

**Comment by gosom** [comment]
I have added a command line parameter that exits the program after a period of inactivity. 

you can use the latest version (see README `-exit-on-inactivity`). 

I am closing the ticket since this is resolved now. 

Please create an issue if you still have problems.

thanks
