### ISSUE TITLE
Any way to specify the coordinates to do the search?

### ISSUE THREAD

**Issue by pabloschz** [gosom/google-maps-scraper#22]
For example search the restaurants nearby the coordinates: 36.71, -4.44

**Comment by gosom** [comment]
This is not supported at the moment. 
The solution is to start the browsers with the specific coordinates.

This can be added in the scrapemate framework.

I will try to add this in the next release

**Comment by pabloschz** [comment]
> This is not supported at the moment. The solution is to start the browsers with the specific coordinates.
> 
> This can be added in the scrapemate framework.
> 
> I will try to add this in the next release

That would be awesome! Nice work man :)

**Comment by gosom** [comment]
@pabloschz this is implemented
