### ISSUE TITLE
Descriptions not extracted or saved during scraping

### ISSUE THREAD

**Issue by jmarsil** [gosom/google-maps-scraper#23]
Wonder if there is a flag to include GMP descriptions during scraping? During testing, I see there is a column for description in results.csv that is exported but there are no descriptions being saved.

**Comment by gosom** [comment]
Will look into that

**Comment by gosom** [comment]
![rest-desc](https://github.com/gosom/google-maps-scraper/assets/454718/b7c5455c-1f73-4089-b193-c3a3c09bb137)

@jmarsil by description you mean the text: `Family-owned restaurant, established in 1893, known for regional cuisine including mussels & fries.` in the attached screenshot ?

This is captured.

**Comment by bloggy** [comment]
@gosom First I want to say thank you for this awesome scraping tool! I downloaded the windows binary and it works fine except that it does not scrape or include the description in the csv table:

![Image](https://github.com/user-attachments/assets/9f9cf21a-9856-45b8-a8c4-b345f540e862)

Can you fix this?
