### ISSUE TITLE
IP rotation 

### ISSUE THREAD

**Issue by FilipByren** [gosom/google-maps-scraper#24]
Any option to set up your ip rotation service on top of this, like IP royal? Like what crawlee has by adding proxy server config https://crawlee.dev/docs/guides/proxy-management

**Comment by gosom** [comment]
I will look into it

**Comment by gosom** [comment]
@FilipByren added SOCKS5 proxy support

**Comment by dlzdrgdr** [comment]
@gosom hey! and is it possible to have HTTP authentication?
