### ISSUE TITLE
Is Directory?

### ISSUE THREAD

**Issue by TEST11R** [gosom/google-maps-scraper#25]
Hi bro i hv installd docker windows and when i run the command it says

# touch results.csv && docker run -v $PWD/example-queries.txt:/example-queries -v $PWD/results.csv:/results.csv gosom/google-maps-scraper -depth 1 -input /example-queries -results /results.csv -exit-on-inactivity 3m
open /results.csv: is a directory
#

**Comment by gosom** [comment]
@TEST11R I never tried that in a windows machine.

Please try to do some debugging on your own .
Thanks

**Comment by TEST11R** [comment]
do u know any projcts that can scrap maps and mail?

**Comment by TEST11R** [comment]
> @TEST11R I never tried that in a windows machine.
> 
> Please try to do some debugging on your own . Thanks

do u know any projcts that can scrap maps and mail? bcoz this maks foldr and says it dirctory..

**Comment by gosom** [comment]
I am closing this issue
