### ISSUE TITLE
Scraper stops after ~3-5 minutes

### ISSUE THREAD

**Issue by yasiralamriki** [gosom/google-maps-scraper#26]

**Comment by TEST11R** [comment]
bro in windows it doesnt even start, can u help ?

**Comment by gosom** [comment]
@riku8405 
What do you mean it stops after 3-5 minutes ? 

This could be normal behaviour .

Please provide more information

**Comment by riku8405** [comment]
> @riku8405 What do you mean it stops after 3-5 minutes ?
> 
> This could be normal behaviour .
> 
> Please provide more information

Theres no mroe completed jobs it gets stuck

**Comment by riku8405** [comment]
I tried using IP rotation with 2 machines, so rotating through  2 IPs and this still happens, I dont know if its an issue with the scraper or if I need more please let me know

**Comment by gosom** [comment]
Do you get any results? 

Do you believe that google blocks the requests ?

**Comment by riku8405** [comment]
I get results, but they stop after about 3-5 minutes, probably but not sure.

**Comment by gosom** [comment]
can you please provide the input ? In particular I am interested in how many queries your input file contains.

**Comment by Neurovert** [comment]
@gosom I think it's about the fact that when using your app, "You've reached the end of the list" is shown in the places pane found in Google maps - after it shows just 20 places. 
I've tried it many times, always same result - but only with query 'accomodation, Czech Republic'. so maybe I have to query each village separately?
When I'm browsing maps with the same query on my normal browser, with Google account logged in, it loads the places endlessly when scrolling.

**Comment by gosom** [comment]
@darealdemayo the browser is not logged in. You need to implement it yourself if you want logged in.
