### ISSUE TITLE
Windows user

### ISSUE THREAD

**Issue by caioyl** [gosom/google-maps-scraper#28]
Dude, it's not exactly an issue. But yes, a doubt. I'm a bit new to Docker and SQL, can you tell me how I can run the program on Windows?

**Comment by Guiponge** [comment]
I'm also curious about this. I'm running it without issue on Manjaro, but I'd like to run it on Win11.  Big noob here. I installed GitHub Desktop and GitBash but I have a hard time running this.

**Comment by gosom** [comment]
I don't have access to a windows machine at the moment. However I am planning to test this on windows and if possibly provide a pre-build binary with instructions.
