### ISSUE TITLE
Docker does not seem to be working

### ISSUE THREAD

**Issue by jontje12** [gosom/google-maps-scraper#29]
Hi,
When running the docker quickstart, it gives the following error:
touch results.csv && docker run -v $PWD/example-queries.txt:/example-queries -v $PWD/results.csv:/results.csv gosom/google-maps-scraper -depth 1 -input /example-queries -results /results.csv -exit-on-inactivity 3m
At line:1 char:19
+ touch results.csv && docker run -v $PWD/example-queries.txt:/example- ...
+                   ~~
The token '&&' is not a valid statement separator in this version.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : InvalidEndOfLine

What can be done to solve this?
Seems like a great program which would have a great contribution.

**Comment by gosom** [comment]
can you please provide more info. Which operating system and the docker version?
