### ISSUE TITLE
Query on google does not match scheduled jobs

### ISSUE THREAD

**Issue by omattman** [gosom/google-maps-scraper#3]
I'm currently testing the accuracy of the scraper and a simple google business result from the query "hair salon in aalborg, denmark" returns +200 results but only 77 jobs are scheduled to be scraped.

Is there any inner workings I should be wary of and possibly be improved on to help you in this matter?

Wonderful tool btw.

**Comment by gosom** [comment]
hello,

have you tried adjusting the depth parameter? By default it's 10 . 

Try this to 20 and let me know 

best

**Comment by omattman** [comment]
Hi @gosom, thanks for getting back this soon.

I've tested the adjustment of depth to be 20 but the change in results was minor.

In the meantime I've managed to combine the results of your scraper with another tool so we can go ahead and close this unless you want more details from me.

Thanks.

**Comment by ignis-tech-solutions** [comment]
@omattman Hi, I'm facing a similar issue of getting the first 120 results only, did you find a workaround for this (other than adding districts/cities for the queries)?
