### ISSUE TITLE
How to retrieve user_reviews?

### ISSUE THREAD

**Issue by m0wer** [gosom/google-maps-scraper#33]
User reviews are always `null` with the default command:

```shell
touch results.csv && docker run -v $PWD/example-queries.txt:/example-queries -v $PWD/results.csv:/results.csv gosom/google-maps-scraper -depth 1 -input /example-queries -results /results.csv -exit-on-inactivity 3m
```

Am I doing something wrong? Is it possible to collect all user reviews of a place?

Thanks!

**Comment by arceushui** [comment]
#34 
If you are interested, I have raised a pull request to resolve the issue. You can just make the changes based on it.

**Comment by m0wer** [comment]
Currently no reviews at all @darealdemayo . Thanks for the fix @arceushui !

**Comment by gosom** [comment]
@arceushui thanks for the fixed. 

just release version 1.1.3 with the provided fix

**Comment by buscandomelavida** [comment]
Hi, I tried a previous version and it worked perfectly until it stopped showing the user_reviews field. I have downloaded version 1.1.3 which I understand fixes this problem, but in all rows it still returns "null". The review_count, review_rating and reviews_per_rating fields are displayed. Does it work correctly and am I doing something wrong?

**Comment by arceushui** [comment]
What is the field name that you are having issue?

**Comment by buscandomelavida** [comment]
user_reviews field

**Comment by DukeLe97** [comment]
i am having the same issue "user_reviews:null"

**Comment by iamsad5566** [comment]
@DukeLe97 , @buscandomelavida  I sent a PR to solve the above issue, you could take it a shot

**Comment by DukeLe97** [comment]
Thanks for your contribution @iamsad5566 , is there any way to get more user_reviews? Now, it only gets 8 user_reviews per place

**Comment by MartiRiusO** [comment]
@iamsad5566 Do you know how to add a new column to find out which prompt the line refers to? 😊

**Comment by MartiRiusO** [comment]
@iamsad5566 the PR isn't working if you change the example-queries. had you seen it?
