### ISSUE TITLE
High memory usage when scraping lot of queries

### ISSUE THREAD

**Issue by admbyz** [gosom/google-maps-scraper#35]
Hi,
Big thanks for the tool. It is wonderful and do the job well but i have a problem about memory usage.

I am using scraper with
./google-maps-scraper -input keyword.txt -results results.csv -exit-on-inactivity 3m -c 1 -depth 14

keyword.txt have like ~400-500 queries after running 4hr+ basically program consumes all of the ram (16gb) available then crashes.  
Both tested windows 10 and xubuntu 22.04 results are same except in linux it is run bit longer due being lightweight OS.

I just made simple script that divide keywords multiple files and then run them synchronously one at a time trough bash and sleeps like 30sec between commands for a workaround.

So the question is memory consumption about memory leak or is it totally normal for that query size?

**Comment by lexciobotariu** [comment]
Hi @admbyz, I have the same problem with 10 cores and 32GB RAM, I was doing 10 queries at the time and run it manually again and again with new queries. 
Would you mind sharing the bash file?
Thanks.

**Comment by gosom** [comment]
@admbyz which go version you use?

**Comment by gosom** [comment]
Do you have the same issue  when you run using a docker container?

**Comment by admbyz** [comment]
@lexciobotariu 
i am running 30 queries per instance with 1 core (-c 1) this should solve your problem if speed is not important.
This is the script that i'm using which search "keywords.txt" and generates keywords01.txt to keywordsn.txt for every 30 queries and finally create run.sh for running scraper synchronously.

make a build.sh that can be executable (chmod +x build.sh) and run it (./build.sh or bash build.sh) after that run the created run.sh file.

```bash
#!/bin/bash

create_keywords_file() {
    local file_prefix="$1"
    local start_line=$2
    local end_line=$3

    sed -n "${start_line},${end_line}p" keywords.txt > "${file_prefix}.txt"
    echo "./google-maps-scraper -input \"${file_prefix}.txt\" -results \"${file_prefix}.csv\" -exit-on-inactivity 3m -c 1 -depth 14 &" >> run.sh
    echo "${file_prefix}=\$!" >> run.sh
    echo "wait \$${file_prefix}" >> run.sh
}

main() {
    if [ ! -f keywords.txt ]; then
        echo "Error: keywords.txt not found!"
        exit 1
    fi

    total_lines=$(wc -l < keywords.txt)
    lines_per_file=30
    num_files=$((total_lines / lines_per_file))
    remainder=$((total_lines % lines_per_file))

    for ((i=1; i<=num_files; i++)); do
        start_line=$(( (i - 1) * lines_per_file + 1 ))
        end_line=$(( i * lines_per_file ))
        file_prefix="keywords$(printf "%02d" $i)"
        create_keywords_file "$file_prefix" "$start_line" "$end_line"
        echo "sleep 30" >> run.sh
    done

    if [ "$remainder" -gt 0 ]; then
        start_line=$((num_files * lines_per_file + 1))
        end_line=$((total_lines))
        file_prefix="keywords$(printf "%02d" $((num_files + 1)))"
        create_keywords_file "$file_prefix" "$start_line" "$end_line"
        echo "sleep 30" >> run.sh
    fi

    chmod +x run.sh
    echo "run.sh file created successfully!"
}

main
```

@gosom 
i am using latest golang on both platform 1.22.1

Didn't used docker and i am off for 3 days after that i will test and comment here again.

**Comment by OSZII** [comment]
@gosom any updates, my 32 GB ram aren't enough?

**Comment by arceushui** [comment]
#7 
I have attached a memory graph in this issue, can help to check it? It seems like playwright didn't close correctly

**Comment by admbyz** [comment]
@gosom 
I tried docker from win10 pc with -c 1 -depth 14 but memory usage was much more because of wsl and got error much faster because docker + wsl started with like 8gb ram usage.

**Comment by gosom** [comment]
The latest release (v1.2.1) has perfomance enhancements and memory usage looks to be stable. 

@admbyz can you try this one ? 

PS. I have only tested in fedora linux but looks good

**Comment by admbyz** [comment]
Sure i will try without splitting my keywords and let you know.
Thanks for the bump.

**Comment by OSZII** [comment]
@gosom Works fine for me too! Thanks Mate!
