### ISSUE TITLE
antivirus flagged as a virus

### ISSUE THREAD

**Issue by rifqy354** [gosom/google-maps-scraper#36]
why my antivirus flag the script as trojan? is it safe to use it
![Screenshot 2024-03-17 160728](https://github.com/gosom/google-maps-scraper/assets/73259705/663ea047-6a14-4ba6-bcfa-75e383e03831)

**Comment by gosom** [comment]
@rifqy354 I am not sure what you have downloaded and from where. 

Can you please provide more information and the whole antivirus message?

**Comment by rifqy354** [comment]
it is my kaspersky antivirus that flagged it as a virus while the scraping is on process.

this is the whole report from kaspersky
Event: Download denied
User: LAPTOP-INHBRJQR\ASUS
User type: Active user
Application name: chrome.exe
Application path: C:\Users\ASUS\AppData\Local\ms-playwright\chromium-978106\chrome-win
Component: Web Anti-Virus
Result description: Blocked
Type: Trojan
Name: HEUR:Trojan.Script.Generic
Precision: Heuristic Analysis
Threat level: High
Object type: File
Object name: elfsight-whatsapp-chat.js?ver=1.2.0
Object path: http://bumisurabaya.com/wp-content/plugins/elfsight-whatsapp-chat-cc/assets
MD5: 83AA8AC89DCE72069AFCAA4CD20FC827
Reason: Expert analysis
Databases release date: Today, 17/03/2024 09:03:00

**Comment by gosom** [comment]
have you enabled to get emails? 

When you do that the program visits an external page (not gmaps). 

see that: `Object path: http://bumisurabaya.com/wp-content/plugins/elfsight-whatsapp-chat-cc/assets`

this has nothing to do with the code in this repo

**Comment by rifqy354** [comment]
i insert -email to script. ok, thanks for helping
