### ISSUE TITLE
The program is taking a very long time to scrape a single query.

### ISSUE THREAD

**Issue by CoolTaher** [gosom/google-maps-scraper#37]
Hello there,

Program consuming a lot of time while simply checking a single query even if i set -depth as 1. any suggestion or help is much appreciated. I'm using VsCode to execute this locally on my machine.

Example - Shopping Malls in thane, India
terminal command : .\google-maps-scraper -depth 1 -input example-queries.txt results test_Scrapping.csv -exit-on-inactivity 3m

it took 2.30 hrs and goes on...... no results are been saved then i shut it off  T-T

Thank you

**Comment by gosom** [comment]
have you tried docker container? Can you provide some more info like OS and the log output?

**Comment by CoolTaher** [comment]
> have you tried docker container? Can you provide some more info like OS and the log output?


My bad its all good I just forgot to put hyphen " - " before results . Thank you for this tool 🔥
