### ISSUE TITLE
o

### ISSUE THREAD

**Issue by liamsegura** [gosom/google-maps-scraper#44]
o

**Comment by liamsegura** [comment]
`"numOfJobsCompleted":191,"numOfJobsFailed":181,`

` touch results.csv && docker run -v $PWD/example-queries.txt:/example-queries -v $PWD/results.csv:/results.csv gosom/google-maps-scraper -depth 20 -c 8 -input /example-queries -results /results.csv -lang en -exit-on-inactivity 3m
`

Shisha bars in Croydon
Shisha bars in Bromley
etc etc...

**Comment by liamsegura** [comment]
i am getting 

WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested

Could this be the problem?

**Comment by SegFault42** [comment]
I had the same issue on my 1 vCPU server.

I had to upgrade.

Where are you trying to run the program ? Which config ?

**Comment by gosom** [comment]
@liamsegura it looks like you use the provided docker image in ARM. I never tried that. 
Better compile and run you own build. 

additionally, you may want to use a more powerfull machine or reduce concurrency. 

Also depth 20 is maybe a bit high, the more you scroll the more slow it is (maybe google throttles?) . 

I recommend you reduce the depth to 10 and do more searches instead (in sub areas).
