### ISSUE TITLE
Input Query in Output CSV

### ISSUE THREAD

**Issue by robertocommit** [gosom/google-maps-scraper#45]
Hi There,

thanks so much for this gem.

I am wondering, is there an easy way to get the input query in the output CSV as additional column?

Have a great day ahead

**Comment by gosom** [comment]
@robertocommit the new release has a feature that can do what you asked. 

in the input CSV add the following:

```
bar in london #!#bar in london
```

`#!#` is a separator. 

Actually, this is to allow users to put a custom ID but you can use it as above. 

(in the CSV there is a new column `input_id` which holds the value after `#!#`.

**Comment by robertocommit** [comment]
It looks great, thanks a ton @gosom
