### ISSUE TITLE
Scraper cannot get google map links

### ISSUE THREAD

**Issue by admbyz** [gosom/google-maps-scraper#53]
I am not sure but i guess google updated places ui and scraper cannot get map links anymore.
Tested both old versions of scraper and latest one on win10 and linux no link was captured.

**Comment by admbyz** [comment]
fresh build with default command. everything was captured except map links.

> ./google-maps-scraper -input example-queries.txt -results restaurants-in-cyprus.csv -exit-on-inactivity 3m

**Comment by admbyz** [comment]
@gosom 
I saw your commit and tried different keywords but no luck. links are not scraped.

**Comment by 0xrsydn** [comment]
> can you write a sample of your input?

is this issue still not fixed? i have same problem which is link is not scraped

**Comment by gosom** [comment]
fixed in v1.2.3
