### ISSUE TITLE
Multithreading

### ISSUE THREAD

**Issue by Bhanu-Prakash01** [gosom/google-maps-scraper#58]
Brother , First of all this project is very good and very helpfull

can u please add multi threading so that will scrape more faster

**Comment by gosom** [comment]
@Bhanu-Prakash01 
It is already utilizing multiple CPUs. 

Increase the concurrency (`-c` flag to the numbers or cores in your computer or a bit more).

If you want faster scale it in multiple machines

**Comment by Bhanu-Prakash01** [comment]
Thq brother
