### ISSUE TITLE
Returns results in San Francisco despite different zip code specified

### ISSUE THREAD

**Issue by R-Rajaie** [gosom/google-maps-scraper#59]
Hi, 

I am attempting to scrape every Whole Foods in the USA. Frankly, the best way I have figured to do this is to use input queries that are essentially "whole foods near zip xxxxx, whole foods near zip xxxxy, etc" for each zip code. However, when I do this, I get tons of duplicate results that are all around San Francisco. I've tried tweaking zip codes and adding quotes, to no avail. 

I think this is because Google Maps' default location opens to San Francisco. In the debug mode it is in incognito, yet still does this.

**Comment by gosom** [comment]
@R-Rajaie I think I can pass the long/lat you want in the browser. Will try to integrate that

**Comment by gosom** [comment]
@R-Rajaie check the new options:

 -geo string
        set geo coordinates for search (e.g., '37.7749,-122.4194')
-zoom int
        set zoom level (0-21) for search
