### ISSUE TITLE
"title is empty" error

### ISSUE THREAD

**Issue by Imploded** [gosom/google-maps-scraper#6]
I've tried running both the local and database methods and for both I'm getting this for every single google maps entry (running on Windows 10):
`{"level":"error","component":"scrapemate","error":"title is empty","time":"2023-07-22T19:24:05.8364593Z","message":"error while processing job"}`

It's successfully outputting the Google Maps url for each location but obviously no information is saved because of this error.

**Comment by gosom** [comment]
Google changes the page layout frequently. 

version v0.9.5 fixes that
