### ISSUE TITLE
user_reviews field, it is writing null for 100% of all the jobs

### ISSUE THREAD

**Issue by juneikerc** [gosom/google-maps-scraper#65]
Hello, I want to thank you for this software and report that in the user_reviews field, it is writing null for 100% of all the jobs. 
![csv](https://github.com/user-attachments/assets/d524022e-b520-4f38-9738-b93fa9098b4d)

**Comment by peshkopy** [comment]
Hello, I notice the same issue.

**Comment by MartiRiusO** [comment]
having the same issue @gosom

**Comment by promani10** [comment]
same issue here 23/09/2024. Will it be corrected soon? BTW congratulations and thanks for your great job!

**Comment by gosom** [comment]
@juneikerc @peshkopy @MartiRiusO @promani10 

https://github.com/gosom/google-maps-scraper/releases/tag/v1.3.3
