### ISSUE TITLE
Record query row

### ISSUE THREAD

**Issue by latot** [gosom/google-maps-scraper#66]
Hi! I think would be very useful save a row that represents which line number is being running from the queries, like an id for the queries.

Thx!

**Comment by gosom** [comment]
hi @latot 

this is already supported. 

![image](https://github.com/user-attachments/assets/e01c59ed-9cae-483d-9efa-71e771dd79d1)

modify your input file to create a custom id according to the above format. 

So your keywords should be like:

```
keyword1 #!#1
keyword2 #!#2
```

and the results will have this as an id.

let me know if that works for you

best

**Comment by latot** [comment]
great thx! I didn't found! was in the docs all the time.

I'll reopen if I find something!
