### ISSUE TITLE
Need help with the Google Map scraper Algorithm

### ISSUE THREAD

**Issue by HafizTariq-Dev** [gosom/google-maps-scraper#75]
Hi @gosom 

I would like to thank you to everyone who has contributed in this great tool which is helping a lot of businesses.
I'm coming from the **_JavaScript background_** and building the scraper with the same feature using [Crawlee](https://crawlee.dev/)

It has great built in features for scrapping.

When time comes to scrap the business information from Google Maps then I need help to know the algorithm behind your scraper.
**How we move from one coordinates to the other?**

As for one keyword, Google return **120 results Maximum** so how your code move to the next closed business information?
**_How it keep moving to next closest business?_**

Can you please share the files where this scraper code is written or share the algorithm so I can write the code in JavaScript?

I look forward to your kind, quick, and positive response.

Thank You

**Comment by gosom** [comment]
hi,

please check the code in this folder:

https://github.com/gosom/google-maps-scraper/tree/main/gmaps
