### ISSUE TITLE
the phone numbers comes up with a equal to sign

### ISSUE THREAD

**Issue by todobig** [gosom/google-maps-scraper#8]
![image](https://github.com/gosom/google-maps-scraper/assets/50915354/c8d75253-297c-4211-8b47-e7226e535f7a)
the phone numbers looks broken

**Comment by gosom** [comment]
I cannot reproduce the the above. Can you sent me an example query that gives these results?

**Comment by todobig** [comment]
[florida2.csv](https://github.com/gosom/google-maps-scraper/files/12179716/florida2.csv)
It basically considering the + Infront of the numbers 
any way we can sanitize it?

**Comment by gosom** [comment]
@todobig I don't see any error here. The + (plus) in front of the phone is valid. 

you can remove it in a post processing
