### ISSUE TITLE
How to get the Feautred Image

### ISSUE THREAD

**Issue by Chetan11-dev** [gosom/google-maps-scraper#9]
Hello Georgios, 
Great Work especially the Kuberentes Integration. 
Also, my question is how did you get the featured image for google-maps-scraping topic?
![Screenshot (529)](https://github.com/gosom/google-maps-scraper/assets/53407137/5f94248f-fa8a-47e8-8e2a-853aeef55a67)

Thanks, 
Chetan

**Comment by Chetan11-dev** [comment]
Also, I see you are looking for a maintainer. You can use my google-maps-scraper [HERE](https://drive.google.com/file/d/1Y1hcDHuViaORufFTi4kmVM7wwgI30_oB/view)! and read Project README.md [HERE](https://chetan-jain-omkar.notion.site/chetan-jain-omkar/Google-Maps-Scraper-652242bb7d3d46c9adaf305f912cf55b) to learn to use the Scraper. especially see `get_more_data.js` you will really like to integrate that part. 
It is brilliant and scrapers 30+ Data Points, 120 Google Maps Result in 2.5 minutes.  
It is MIT licensed You can add as much code as you want. I have no issue.

**Comment by gosom** [comment]
@Chetan11-dev thanks for sharing your project. 

To add a featured image go to Settings -> Social Preview

**Comment by Chetan11-dev** [comment]
Thanks
