### ISSUE TITLE
Speed enhancement

### ISSUE THREAD

**Issue by graysuit** [gosom/google-maps-scraper#95]
I think google map heavily uses images to display map etc
This might slowdown scraping

What about using --blink-settings=imagesEnabled=false in selenium ?
It will prevent images and webpage load faster

**Comment by gosom** [comment]
1. The scraper does not use selenium .

2. The images should be disabled. Did you found out that they are enabled ?

**Comment by graysuit** [comment]
Yes images are disabled. 

Really sorry. I misunderstood that map tiles were made of images (like regrid).
Not sure, but they use something other than images.

**Comment by gosom** [comment]
@graysuit np
