### ISSUE TITLE
API access

### ISSUE THREAD

**Issue by BjoernRave** [gosom/google-maps-scraper#99]
is it currently possible to somehow start a job from my javascript code via a request to some endpoint?

**Comment by gosom** [comment]
I am planning adding a REST API in the beginning of the new year.

**Comment by BjoernRave** [comment]
I added an API to the project in my fork here: https://github.com/BjoernRave/google-maps-scraper. I could file a PR

**Comment by gosom** [comment]
@BjoernRave I have already added that when I seen your message. 

thanks for your offer. 

you can find the implementation in the new release : https://github.com/gosom/google-maps-scraper/releases/tag/v1.7.0

**Comment by BjoernRave** [comment]
Cool, will check it out :)
